# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
knowledge_base:
  jira:
    usage: "enabled"
    project_keys:
      - "SCRUM"
chat:
  integrations:
    jira:
      usage: "enabled"
